name: WP_Ikigai CI/CD

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [8.2]
        wp-versions: ['6.7.2']

    name: PHP ${{ matrix.php-versions }} / WP ${{ matrix.wp-versions }} Test

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, intl, mysqli
        tools: composer, phpcs, phpunit

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Check coding standards
      run: composer run-script phpcs

    - name: Run tests
      run: composer run-script test

  build:
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        tools: composer

    - name: Install dependencies
      run: composer install --no-dev --prefer-dist --no-progress

    - name: Create build directory
      run: |
        mkdir -p build
        rsync -av --exclude-from=.distignore . build/

    - name: Create zip
      run: |
        cd build
        zip -r ../wp_ikigai.zip .

    - name: Upload build as artifact
      uses: actions/upload-artifact@v3
      with:
        name: plugin-build
        path: wp_ikigai.zip

  deploy:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download build
      uses: actions/download-artifact@v3
      with:
        name: plugin-build

    - name: WordPress.org Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: wp_ikigai
