name: WP_Ikigai CI/CD

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main, develop ]

jobs:
  php:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: xdebug
        tools: composer:v2
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, json, pdo, pdo_mysql, session, tokenizer, zip

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: |
          vendor/
          ~/.composer/cache
        key: ${{ runner.os }}-php-8.2-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-8.2-composer-
          ${{ runner.os }}-composer-

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Check PHP Code Style
      run: composer run phpcs
      continue-on-error: true

    - name: Fix PHP Code Style
      run: composer run phpcbf
      continue-on-error: true

    - name: Setup WordPress Test Environment
      run: |
        bash bin/install-wp-tests.sh wordpress_test root '' localhost 6.7.2
      env:
        WP_TESTS_DIR: /tmp/wordpress-tests-lib
        WP_CORE_DIR: /tmp/wordpress/

    - name: Run PHPUnit Tests
      run: composer run test
      env:
        WP_TESTS_DIR: /tmp/wordpress-tests-lib
        WP_CORE_DIR: /tmp/wordpress/

    - name: Upload Coverage Report
      uses: codecov/codecov-action@v3
      with:
        file: coverage-report/coverage.xml
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      if: failure()
      with:
        commit-message: "style: Fix PHP code style issues"
        title: "style: Fix PHP code style issues"
        body: |
          Automated fixes for PHP code style issues
          
          This PR was automatically created to fix PHP code style issues.
          Please review the changes and merge if appropriate.
          
          Environment:
          - PHP: 8.2
          - WordPress: 6.7.2
        branch: fix/php-code-style
        delete-branch: true
        labels: |
          automated
          code-style
          php-8.2

  build:
    needs: php
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer:v2

    - name: Install dependencies
      run: composer install --no-dev --prefer-dist --no-progress

    - name: Create build directory
      run: |
        mkdir -p build
        rsync -av --exclude-from=.distignore . build/

    - name: Create zip
      run: |
        cd build
        zip -r ../wp-ikigai.zip .

    - name: Upload build as artifact
      uses: actions/upload-artifact@v3
      with:
        name: plugin-build
        path: wp-ikigai.zip

  deploy:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download build
      uses: actions/download-artifact@v3
      with:
        name: plugin-build

    - name: WordPress.org Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: wp-ikigai
