name: WP_Ikigai CI/CD

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
  pull_request:
    branches:
      - main

jobs:
  php:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP and required tools
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: xdebug
        tools: composer:v2, phpcs, phpunit
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, json, pdo, pdo_mysql, session, tokenizer, zip

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: |
          vendor/
          ~/.composer/cache
        key: ${{ runner.os }}-php-8.2-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-8.2-composer-
          ${{ runner.os }}-composer-

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Check PHP Code Style
      run: composer run phpcs
      continue-on-error: true

    - name: Fix PHP Code Style
      run: composer run phpcbf
      continue-on-error: true

    - name: Setup WordPress Test Environment
      run: |
        mkdir -p /tmp/wordpress-tests-lib
        git clone --depth=1 --branch=6.7.2 https://github.com/WordPress/wordpress-develop.git /tmp/wordpress-develop
        cp -r /tmp/wordpress-develop/tests/phpunit/includes/* /tmp/wordpress-tests-lib/
        cp -r /tmp/wordpress-develop/tests/phpunit/data/* /tmp/wordpress-tests-lib/
      env:
        WP_TESTS_DIR: /tmp/wordpress-tests-lib
        WP_CORE_DIR: /tmp/wordpress/

    - name: Run PHPUnit Tests
      run: composer run test
      env:
        WP_TESTS_DIR: /tmp/wordpress-tests-lib
        WP_CORE_DIR: /tmp/wordpress/

    - name: Upload Coverage Report
      uses: codecov/codecov-action@v3
      with:
        file: coverage-report/coverage.xml
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      if: failure()
      with:
        commit-message: "style: Fix PHP code style issues"
        title: "style: Fix PHP code style issues"
        body: |
          Automated fixes for PHP code style issues
          
          This PR was automatically created to fix PHP code style issues.
          Please review the changes and merge if appropriate.
          
          Environment:
          - PHP: 8.2
          - WordPress: 6.7.2
        branch: fix/php-code-style
        delete-branch: true
        labels: |
          automated
          code-style
          php-8.2

  build:
    needs: php
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create Release ZIP
      run: |
        mkdir -p build
        rsync -av --exclude-from=.distignore . build/
        cd build
        zip -r ../wp-ikigai.zip .

    - name: Upload ZIP as artifact
      uses: actions/upload-artifact@v3
      with:
        name: plugin-build
        path: wp-ikigai.zip
