name: PHP Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  php:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2']
        include:
          - php: '8.2'
            coverage: true

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: ${{ matrix.coverage || false }}
        tools: composer:v2
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, json, pdo, pdo_mysql, session, tokenizer, zip

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: |
          vendor/
          ~/.composer/cache
        key: ${{ runner.os }}-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php }}-composer-
          ${{ runner.os }}-composer-

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Check PHP Code Style
      run: composer run phpcs
      continue-on-error: true

    - name: Fix PHP Code Style
      run: composer run phpcbf
      continue-on-error: true

    - name: Setup WordPress Test Environment
      run: |
        bash bin/install-wp-tests.sh wordpress_test root '' localhost latest
      env:
        WP_TESTS_DIR: /tmp/wordpress-tests-lib
        WP_CORE_DIR: /tmp/wordpress/

    - name: Run PHPUnit Tests
      run: composer run test
      env:
        WP_TESTS_DIR: /tmp/wordpress-tests-lib
        WP_CORE_DIR: /tmp/wordpress/
        PHP_VERSION: ${{ matrix.php }}

    - name: Upload Coverage Report
      if: matrix.coverage
      uses: codecov/codecov-action@v3
      with:
        file: coverage-report/coverage.xml
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      if: failure()
      with:
        commit-message: "style: Fix PHP code style issues"
        title: "style: Fix PHP code style issues"
        body: |
          Automated fixes for PHP code style issues
          
          This PR was automatically created to fix PHP code style issues.
          Please review the changes and merge if appropriate.
          
          PHP Version: ${{ matrix.php }}
        branch: fix/php-code-style-${{ matrix.php }}
        delete-branch: true
        labels: |
          automated
          code-style
          php-${{ matrix.php }}
