name: PHP Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  php:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: xdebug
        tools: composer:v2

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Check PHP Code Style
      run: composer run phpcs

    - name: Fix PHP Code Style
      run: composer run phpcbf

    - name: Run PHPUnit Tests
      run: composer run test

    - name: Upload Coverage Report
      uses: codecov/codecov-action@v3
      with:
        file: coverage-report/coverage.xml
        fail_ci_if_error: true

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "style: Fix PHP code style issues"
        title: "style: Fix PHP code style issues"
        body: "Automated fixes for PHP code style issues"
        branch: fix/php-code-style
        delete-branch: true
